// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gffizovebjgnyhxixvia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZml6b3ZlYmpnbnloeGl4dmlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDE0NjksImV4cCI6MjA2MDExNzQ2OX0.dfFkQRTndj13b4Xa5Hjl27xl3sMzSqSjbQSRFlrnXVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);